# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/idiom_game.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_idiom_game(object):
    def setupUi(self, idiom_game):
        idiom_game.setObjectName("idiom_game")
        idiom_game.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(idiom_game)
        self.centralwidget.setObjectName("centralwidget")
        self.bt1 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1.setGeometry(QtCore.QRect(100, 200, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt1.setFont(font)
        self.bt1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt1.setText("")
        self.bt1.setObjectName("bt1")
        self.bt2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2.setGeometry(QtCore.QRect(190, 200, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt2.setFont(font)
        self.bt2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt2.setText("")
        self.bt2.setObjectName("bt2")
        self.bt3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3.setGeometry(QtCore.QRect(280, 200, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt3.setFont(font)
        self.bt3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt3.setText("")
        self.bt3.setObjectName("bt3")
        self.bt4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4.setGeometry(QtCore.QRect(370, 200, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt4.setFont(font)
        self.bt4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt4.setText("")
        self.bt4.setObjectName("bt4")
        self.bt5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5.setGeometry(QtCore.QRect(460, 200, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt5.setFont(font)
        self.bt5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt5.setText("")
        self.bt5.setObjectName("bt5")
        self.bt6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6.setGeometry(QtCore.QRect(550, 200, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt6.setFont(font)
        self.bt6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt6.setText("")
        self.bt6.setObjectName("bt6")
        self.bt7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7.setGeometry(QtCore.QRect(640, 200, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt7.setFont(font)
        self.bt7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt7.setText("")
        self.bt7.setObjectName("bt7")
        self.bt8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8.setGeometry(QtCore.QRect(100, 280, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt8.setFont(font)
        self.bt8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt8.setText("")
        self.bt8.setObjectName("bt8")
        self.bt9 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9.setGeometry(QtCore.QRect(190, 280, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt9.setFont(font)
        self.bt9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt9.setText("")
        self.bt9.setObjectName("bt9")
        self.bt10 = QtWidgets.QPushButton(self.centralwidget)
        self.bt10.setGeometry(QtCore.QRect(280, 280, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt10.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt10.setFont(font)
        self.bt10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt10.setText("")
        self.bt10.setObjectName("bt10")
        self.bt11 = QtWidgets.QPushButton(self.centralwidget)
        self.bt11.setGeometry(QtCore.QRect(370, 280, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt11.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt11.setFont(font)
        self.bt11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt11.setText("")
        self.bt11.setObjectName("bt11")
        self.bt12 = QtWidgets.QPushButton(self.centralwidget)
        self.bt12.setGeometry(QtCore.QRect(460, 280, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt12.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt12.setFont(font)
        self.bt12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt12.setText("")
        self.bt12.setObjectName("bt12")
        self.bt13 = QtWidgets.QPushButton(self.centralwidget)
        self.bt13.setGeometry(QtCore.QRect(550, 280, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt13.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt13.setFont(font)
        self.bt13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt13.setText("")
        self.bt13.setObjectName("bt13")
        self.bt14 = QtWidgets.QPushButton(self.centralwidget)
        self.bt14.setGeometry(QtCore.QRect(640, 280, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt14.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt14.setFont(font)
        self.bt14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt14.setText("")
        self.bt14.setObjectName("bt14")
        self.bt15 = QtWidgets.QPushButton(self.centralwidget)
        self.bt15.setGeometry(QtCore.QRect(100, 360, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt15.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt15.setFont(font)
        self.bt15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt15.setText("")
        self.bt15.setObjectName("bt15")
        self.bt16 = QtWidgets.QPushButton(self.centralwidget)
        self.bt16.setGeometry(QtCore.QRect(190, 360, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt16.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt16.setFont(font)
        self.bt16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt16.setText("")
        self.bt16.setObjectName("bt16")
        self.bt17 = QtWidgets.QPushButton(self.centralwidget)
        self.bt17.setGeometry(QtCore.QRect(280, 360, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt17.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt17.setFont(font)
        self.bt17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt17.setText("")
        self.bt17.setObjectName("bt17")
        self.bt18 = QtWidgets.QPushButton(self.centralwidget)
        self.bt18.setGeometry(QtCore.QRect(370, 360, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt18.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt18.setFont(font)
        self.bt18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt18.setText("")
        self.bt18.setObjectName("bt18")
        self.bt19 = QtWidgets.QPushButton(self.centralwidget)
        self.bt19.setGeometry(QtCore.QRect(460, 360, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt19.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt19.setFont(font)
        self.bt19.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt19.setText("")
        self.bt19.setObjectName("bt19")
        self.bt20 = QtWidgets.QPushButton(self.centralwidget)
        self.bt20.setGeometry(QtCore.QRect(550, 360, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt20.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt20.setFont(font)
        self.bt20.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt20.setText("")
        self.bt20.setObjectName("bt20")
        self.bt21 = QtWidgets.QPushButton(self.centralwidget)
        self.bt21.setGeometry(QtCore.QRect(640, 360, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt21.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt21.setFont(font)
        self.bt21.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt21.setText("")
        self.bt21.setObjectName("bt21")
        self.bt22 = QtWidgets.QPushButton(self.centralwidget)
        self.bt22.setGeometry(QtCore.QRect(100, 440, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt22.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt22.setFont(font)
        self.bt22.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt22.setText("")
        self.bt22.setObjectName("bt22")
        self.bt23 = QtWidgets.QPushButton(self.centralwidget)
        self.bt23.setGeometry(QtCore.QRect(190, 440, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt23.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt23.setFont(font)
        self.bt23.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt23.setText("")
        self.bt23.setObjectName("bt23")
        self.bt24 = QtWidgets.QPushButton(self.centralwidget)
        self.bt24.setGeometry(QtCore.QRect(280, 440, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt24.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt24.setFont(font)
        self.bt24.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt24.setText("")
        self.bt24.setObjectName("bt24")
        self.bt25 = QtWidgets.QPushButton(self.centralwidget)
        self.bt25.setGeometry(QtCore.QRect(370, 440, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt25.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt25.setFont(font)
        self.bt25.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt25.setText("")
        self.bt25.setObjectName("bt25")
        self.bt26 = QtWidgets.QPushButton(self.centralwidget)
        self.bt26.setGeometry(QtCore.QRect(460, 440, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt26.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt26.setFont(font)
        self.bt26.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt26.setText("")
        self.bt26.setObjectName("bt26")
        self.bt27 = QtWidgets.QPushButton(self.centralwidget)
        self.bt27.setGeometry(QtCore.QRect(550, 440, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt27.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt27.setFont(font)
        self.bt27.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt27.setText("")
        self.bt27.setObjectName("bt27")
        self.bt28 = QtWidgets.QPushButton(self.centralwidget)
        self.bt28.setGeometry(QtCore.QRect(640, 440, 71, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt28.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt28.setFont(font)
        self.bt28.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt28.setText("")
        self.bt28.setObjectName("bt28")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(100, 260, 611, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 200, 20, 301))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(260, 200, 20, 301))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(350, 200, 20, 301))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(440, 200, 20, 301))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(530, 200, 20, 301))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(620, 200, 20, 301))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(100, 340, 611, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(100, 420, 611, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(320, 50, 171, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.time_lb = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_lb.setFont(font)
        self.time_lb.setText("")
        self.time_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.time_lb.setObjectName("time_lb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.time_lb)
        self.exit_bt = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.exit_bt.setGeometry(QtCore.QRect(660, 0, 131, 48))
        self.exit_bt.setObjectName("exit_bt")
        self.tip_bt = QtWidgets.QPushButton(self.centralwidget)
        self.tip_bt.setGeometry(QtCore.QRect(660, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tip_bt.setFont(font)
        self.tip_bt.setObjectName("tip_bt")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 101, 205))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fi_lb1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fi_lb1.setFont(font)
        self.fi_lb1.setText("")
        self.fi_lb1.setObjectName("fi_lb1")
        self.verticalLayout.addWidget(self.fi_lb1)
        self.fi_lb2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fi_lb2.setFont(font)
        self.fi_lb2.setText("")
        self.fi_lb2.setObjectName("fi_lb2")
        self.verticalLayout.addWidget(self.fi_lb2)
        self.fi_lb3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fi_lb3.setFont(font)
        self.fi_lb3.setText("")
        self.fi_lb3.setObjectName("fi_lb3")
        self.verticalLayout.addWidget(self.fi_lb3)
        self.fi_lb4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fi_lb4.setFont(font)
        self.fi_lb4.setText("")
        self.fi_lb4.setObjectName("fi_lb4")
        self.verticalLayout.addWidget(self.fi_lb4)
        self.fi_lb5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fi_lb5.setFont(font)
        self.fi_lb5.setText("")
        self.fi_lb5.setObjectName("fi_lb5")
        self.verticalLayout.addWidget(self.fi_lb5)
        self.fi_lb6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fi_lb6.setFont(font)
        self.fi_lb6.setText("")
        self.fi_lb6.setObjectName("fi_lb6")
        self.verticalLayout.addWidget(self.fi_lb6)
        self.fi_lb7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fi_lb7.setFont(font)
        self.fi_lb7.setText("")
        self.fi_lb7.setObjectName("fi_lb7")
        self.verticalLayout.addWidget(self.fi_lb7)
        idiom_game.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(idiom_game)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        idiom_game.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(idiom_game)
        self.statusbar.setObjectName("statusbar")
        idiom_game.setStatusBar(self.statusbar)

        self.retranslateUi(idiom_game)
        QtCore.QMetaObject.connectSlotsByName(idiom_game)

    def retranslateUi(self, idiom_game):
        _translate = QtCore.QCoreApplication.translate
        idiom_game.setWindowTitle(_translate("idiom_game", "成语消消看"))
        self.label.setText(_translate("idiom_game", "时间："))
        self.exit_bt.setText(_translate("idiom_game", "退出游戏"))
        self.tip_bt.setText(_translate("idiom_game", "提示"))
