# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/poem_game.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_poem_game(object):
    def setupUi(self, poem_game):
        poem_game.setObjectName("poem_game")
        poem_game.resize(800, 618)
        font = QtGui.QFont()
        font.setPointSize(9)
        poem_game.setFont(font)
        self.centralwidget = QtWidgets.QWidget(poem_game)
        self.centralwidget.setObjectName("centralwidget")
        self.ok_bt = QtWidgets.QPushButton(self.centralwidget)
        self.ok_bt.setGeometry(QtCore.QRect(440, 500, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ok_bt.setFont(font)
        self.ok_bt.setObjectName("ok_bt")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 170, 461, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.option1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.option1.setFont(font)
        self.option1.setText("")
        self.option1.setObjectName("option1")
        self.verticalLayout.addWidget(self.option1)
        self.option2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.option2.setFont(font)
        self.option2.setText("")
        self.option2.setObjectName("option2")
        self.verticalLayout.addWidget(self.option2)
        self.option3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.option3.setFont(font)
        self.option3.setText("")
        self.option3.setObjectName("option3")
        self.verticalLayout.addWidget(self.option3)
        self.option4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.option4.setFont(font)
        self.option4.setText("")
        self.option4.setObjectName("option4")
        self.verticalLayout.addWidget(self.option4)
        self.tip_bt = QtWidgets.QPushButton(self.centralwidget)
        self.tip_bt.setGeometry(QtCore.QRect(230, 500, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tip_bt.setFont(font)
        self.tip_bt.setObjectName("tip_bt")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(90, 90, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.question.setFont(font)
        self.question.setText("")
        self.question.setAlignment(QtCore.Qt.AlignCenter)
        self.question.setObjectName("question")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 234, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ans_num = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ans_num.setFont(font)
        self.ans_num.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ans_num.setProperty("intValue", 0)
        self.ans_num.setObjectName("ans_num")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ans_num)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.life_num = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.life_num.setFont(font)
        self.life_num.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.life_num.setObjectName("life_num")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.life_num)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tip_num = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(3)
        self.tip_num.setFont(font)
        self.tip_num.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tip_num.setObjectName("tip_num")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tip_num)
        self.exit_bt = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.exit_bt.setGeometry(QtCore.QRect(660, 10, 131, 48))
        self.exit_bt.setObjectName("exit_bt")
        poem_game.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(poem_game)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        poem_game.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(poem_game)
        self.statusbar.setObjectName("statusbar")
        poem_game.setStatusBar(self.statusbar)

        self.retranslateUi(poem_game)
        QtCore.QMetaObject.connectSlotsByName(poem_game)

    def retranslateUi(self, poem_game):
        _translate = QtCore.QCoreApplication.translate
        poem_game.setWindowTitle(_translate("poem_game", "诗词问答"))
        self.ok_bt.setText(_translate("poem_game", "确定"))
        self.tip_bt.setText(_translate("poem_game", "提示"))
        self.label_2.setText(_translate("poem_game", "共完成题数："))
        self.label_3.setText(_translate("poem_game", "剩余作答机会："))
        self.label_4.setText(_translate("poem_game", "剩余提示机会："))
        self.exit_bt.setText(_translate("poem_game", "退出游戏"))
